policy:
  type: pi05
  repo_id: steb6/pi0_roboarena_HRII
  device: cuda
  chunk_size: 16
  n_action_steps: 16

dataset:
  repo_id: steb6/roboarena_HRII
  revision: main
  image_transforms:
    enable: true
